# Generated by Django 5.2.4 on 2025-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_emailotp_options_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="user",
            field=models.CharField(max_length=255, verbose_name="Пользователь"),
        ),
    ]
