# Generated by Django 5.2.5 on 2025-08-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailotp_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
