# Generated by Django 5.2.5 on 2025-08-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_favorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.DeleteModel(
            name="Balance",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
