# Generated by Django 5.2.5 on 2025-11-22 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип диска')),
            ],
            options={
                'verbose_name': 'Тип диска',
                'verbose_name_plural': 'Типы дисков',
            },
        ),
        migrations.CreateModel(
            name='TireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_type', models.CharField(max_length=30, verbose_name='Тип шин')),
            ],
        ),
        migrations.CreateModel(
            name='CarAccessorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.availability', verbose_name='Доступность')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='Город')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.condition', verbose_name='Состояние')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.generation', verbose_name='Поколение')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.model', verbose_name='Модель')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Аксессуар и мультимедиа',
                'verbose_name_plural': 'Аксессуары и мультимедиа',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarAccessoriesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accessories_images/', verbose_name='Фото')),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_parts.caraccessorie')),
            ],
        ),
        migrations.CreateModel(
            name='CarDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastener_driling', models.CharField(max_length=30, verbose_name='Крепеж/Сверловка')),
                ('disk_diameter', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Диаметр дисков')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена')),
                ('year_of_production', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.availability', verbose_name='Доступность')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='Город')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.condition', verbose_name='Состояние')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.generation', verbose_name='Поколение')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.model', verbose_name='Модель')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.region', verbose_name='Регион')),
                ('disk_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_parts.disktype', verbose_name='Тип диска')),
            ],
            options={
                'verbose_name': 'Диск',
                'verbose_name_plural': 'Диски',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarDiskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_disk/', verbose_name='Изображение')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.cardisk', verbose_name='Диск')),
            ],
        ),
        migrations.CreateModel(
            name='CarForPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.availability', verbose_name='Доступность')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='Город')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.condition', verbose_name='Состояние')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.generation', verbose_name='Поколение')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.model', verbose_name='Модель')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Машина на запчасти',
                'verbose_name_plural': 'Машины на запчасти',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarForPartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('car_for_parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.carforpart', verbose_name='Машина на запчасти')),
            ],
            options={
                'verbose_name': 'Фотография машины на запчасти',
                'verbose_name_plural': 'Фотографии машин на запчасти',
            },
        ),
        migrations.CreateModel(
            name='CarOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.availability', verbose_name='Доступность')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='Город')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.condition', verbose_name='Состояние')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.generation', verbose_name='Поколение')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.model', verbose_name='Модель')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Масло и химия',
                'verbose_name_plural': 'Масла и химия',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarOilsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('car_oils', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.caroil', verbose_name='Масло и химия')),
            ],
            options={
                'verbose_name': 'Фото масла и химии',
                'verbose_name_plural': 'Фото масел и химий',
            },
        ),
        migrations.CreateModel(
            name='CarTire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_width', models.PositiveSmallIntegerField(verbose_name='Ширина шин')),
                ('tire_height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Высота шин')),
                ('tire_size', models.CharField(max_length=30, verbose_name='Размер шин')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.generation', verbose_name='Поколение')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.model', verbose_name='Модель')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('car_tire_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_parts.tiretype', verbose_name='Тип шин')),
            ],
            options={
                'verbose_name': 'Шина',
                'verbose_name_plural': 'Шины',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarTireImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='car_tire_images/', verbose_name='Фото')),
                ('car_tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.cartire', verbose_name='Шины')),
            ],
        ),
        migrations.CreateModel(
            name='PartsAndConsumble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.availability', verbose_name='Доступность')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='Город')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.condition', verbose_name='Состояние')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.generation', verbose_name='Поколение')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.model', verbose_name='Модель')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_and_consumbles', to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Запчасти и расходники',
                'verbose_name_plural': 'Запчасти и расходники',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PartsAndConsumblesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='parts_and_consumbles_images/', verbose_name='Фото запчастей и расходников')),
                ('parts_and_consumbles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_parts.partsandconsumble', verbose_name='Запчасти и расходники')),
            ],
            options={
                'verbose_name': 'Фотография запчасти и расходника',
                'verbose_name_plural': 'Фотографии запчастей и расходников',
            },
        ),
        migrations.CreateModel(
            name='StateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='Город')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Госномер',
                'verbose_name_plural': 'Госномера',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StateNumberImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='state_numbers', verbose_name='Фото')),
                ('state_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.statenumber', verbose_name='Госномер')),
            ],
            options={
                'verbose_name': 'Фото госномер',
                'verbose_name_plural': 'Фото госномеров',
            },
        ),
    ]
