# Generated by Django 5.2.5 on 2025-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroilsimage',
            name='image',
            field=models.ImageField(upload_to='car_oils/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='partsandconsumblesimage',
            name='images',
            field=models.ImageField(upload_to='parts_consumbles_images/', verbose_name='Фото запчастей и расходников'),
        ),
        migrations.AlterField(
            model_name='statenumberimage',
            name='image',
            field=models.ImageField(upload_to='state_numbers/', verbose_name='Фото'),
        ),
    ]
