# Generated by Django 5.2.5 on 2025-11-10 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_parts', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_type', models.CharField(max_length=30, verbose_name='Тип шин')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardisk',
            name='disk_height',
        ),
        migrations.RemoveField(
            model_name='cardisk',
            name='disk_width',
        ),
        migrations.AddField(
            model_name='cardisk',
            name='fastener_driling',
            field=models.CharField(default=1, max_length=30, verbose_name='Крепеж/Сверловка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wheelimage',
            name='image',
            field=models.ImageField(upload_to='car_disk/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='CarTire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_width', models.PositiveSmallIntegerField(verbose_name='Ширина шин')),
                ('tire_height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Высота шин')),
                ('tire_size', models.CharField(max_length=30, verbose_name='Размер шин')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Цена')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.generation', verbose_name='Поколение')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.model', verbose_name='Модель')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('car_tire_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_parts.tiretype', verbose_name='Тип шин')),
            ],
            options={
                'verbose_name': 'Шины',
                'verbose_name_plural': 'Шины',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarTireImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/', verbose_name='Фото')),
                ('car_tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_parts.cartire', verbose_name='Шины')),
            ],
        ),
        migrations.DeleteModel(
            name='DiskHeight',
        ),
        migrations.DeleteModel(
            name='DiskWidth',
        ),
    ]
