# Generated by Django 5.2.4 on 2025-07-29 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Body",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Тип кузова")),
            ],
            options={
                "verbose_name": "Тип кузова",
                "verbose_name_plural": "Тип кузовов",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Цвет")),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвет",
            },
        ),
        migrations.CreateModel(
            name="CustomClearence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_clearence",
                    models.BooleanField(default=True, verbose_name="Растаможка"),
                ),
            ],
            options={
                "verbose_name": "Растаможка",
                "verbose_name_plural": "Растаможка",
            },
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Тип привода")),
            ],
        ),
        migrations.CreateModel(
            name="EngineCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="Объем двигателя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Объем двигателя",
                "verbose_name_plural": "Объем двигателей",
            },
        ),
        migrations.CreateModel(
            name="EngineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Тип двигателя")),
            ],
            options={
                "verbose_name": "Тип двигателя",
                "verbose_name_plural": "Тип двигателей",
            },
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="Вариант обмена"),
                ),
            ],
            options={
                "verbose_name": "Вариант обмена",
                "verbose_name_plural": "Вариант обмена",
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration", models.CharField(max_length=50, verbose_name="Учет")),
            ],
            options={
                "verbose_name": "Учет",
                "verbose_name_plural": "Учет",
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("premium", "Премиум"), ("vip", "Вип")],
                        max_length=50,
                        verbose_name="Тип тарифа",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена (сом)"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="Срок действия (в днях)"),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
            },
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=40, verbose_name="Коробка передач"),
                ),
            ],
            options={
                "verbose_name": "Коробка передач",
                "verbose_name_plural": "Коробки передач",
            },
        ),
        migrations.CreateModel(
            name="WheelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wheel_type_name",
                    models.CharField(max_length=40, verbose_name="Руль"),
                ),
            ],
            options={
                "verbose_name": "Тип руля",
                "verbose_name_plural": "Тип руля",
            },
        ),
        migrations.CreateModel(
            name="YearOfProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveBigIntegerField(verbose_name="Год выпуска")),
            ],
            options={
                "verbose_name": "Год выпуска",
                "verbose_name_plural": "Год выпуска",
            },
        ),
        migrations.CreateModel(
            name="CarConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.body",
                        verbose_name="Тип кузова",
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.generation",
                        verbose_name="Поколение",
                    ),
                ),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.mark",
                        verbose_name="Марка",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.model",
                        verbose_name="Модель",
                    ),
                ),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.drive",
                        verbose_name="Тип привода",
                    ),
                ),
                (
                    "engine_capacity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.enginecapacity",
                        verbose_name="Объем двигателя",
                    ),
                ),
                (
                    "engine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.enginetype",
                        verbose_name="Тип двигателя",
                    ),
                ),
                (
                    "transmission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.transmission",
                        verbose_name="Коробка передач",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=1, max_digits=9, verbose_name="Цена"
                    ),
                ),
                (
                    "engine_power",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Мощность двигателя",
                    ),
                ),
                ("car_meleage", models.PositiveBigIntegerField(verbose_name="Пробег")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "urgency_of_announcencenment",
                    models.CharField(
                        max_length=30, verbose_name="Срочность объявления"
                    ),
                ),
                (
                    "availability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.avalability",
                        verbose_name="Доступность",
                    ),
                ),
                (
                    "car_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.condition",
                        verbose_name="Состояние машины",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Профиль",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.region",
                        verbose_name="Регион",
                    ),
                ),
                (
                    "car_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.carconfig",
                        verbose_name="Конфигурация",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="car_images", verbose_name="Фото"),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.carannouncement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Категория")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategory",
                        to="main.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AddField(
            model_name="carannouncement",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="announcements_by_category",
                to="main.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="carannouncement",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.color",
                verbose_name="Цвет автомобиля",
            ),
        ),
        migrations.AddField(
            model_name="carannouncement",
            name="custom_clearence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.customclearence",
                verbose_name="Состояние",
            ),
        ),
        migrations.AddField(
            model_name="carannouncement",
            name="exchange",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.exchange",
                verbose_name="Обмен",
            ),
        ),
        migrations.AddField(
            model_name="carannouncement",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.registration",
                verbose_name="Регистрация",
            ),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Начало действия",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Конец действия"
                    ),
                ),
                (
                    "car_announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="main.carannouncement",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.tariff",
                        verbose_name="Тариф",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carannouncement",
            name="wheel_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.wheeltype",
                verbose_name="Тип руля",
            ),
        ),
        migrations.AddField(
            model_name="carannouncement",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.yearofproduction",
                verbose_name="Год выпуска",
            ),
        ),
    ]
