# Generated by Django 5.2.4 on 2025-07-21 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Доступность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступность",
                "verbose_name_plural": "Доступность",
            },
        ),
        migrations.CreateModel(
            name="BodyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_type_name",
                    models.CharField(max_length=40, verbose_name="Тип кузова"),
                ),
            ],
            options={
                "verbose_name": "Тип кузова",
                "verbose_name_plural": "Тип кузовов",
            },
        ),
        migrations.CreateModel(
            name="CarCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(max_length=100, verbose_name="Состояние"),
                ),
            ],
            options={
                "verbose_name": "Состояние",
                "verbose_name_plural": "Состояния",
            },
        ),
        migrations.CreateModel(
            name="CarMeleage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_meleage",
                    models.PositiveIntegerField(verbose_name="Пробег машины"),
                ),
            ],
            options={
                "verbose_name": "Пробег",
                "verbose_name_plural": "Пробег",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=50, verbose_name="Название города"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColorOfCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_of_car",
                    models.CharField(max_length=100, verbose_name="Цвет машины"),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвет",
            },
        ),
        migrations.CreateModel(
            name="CustomClearence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_clearence",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Растаможка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Растаможка",
                "verbose_name_plural": "Растаможка",
            },
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drive_name",
                    models.CharField(max_length=40, verbose_name="Тип привода"),
                ),
            ],
            options={
                "verbose_name": "Тип привода",
                "verbose_name_plural": "Тип приводов",
            },
        ),
        migrations.CreateModel(
            name="EngineCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine_capacity",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="Объем двигателя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Объем двигателя",
                "verbose_name_plural": "Объем двигателя",
            },
        ),
        migrations.CreateModel(
            name="EnginePower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine_power",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        verbose_name="Мощность двигателя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мощность двигателя",
                "verbose_name_plural": "Мощность двигателя",
            },
        ),
        migrations.CreateModel(
            name="EngineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine_name",
                    models.CharField(max_length=40, verbose_name="Тип двигателя"),
                ),
            ],
            options={
                "verbose_name": "Тип двигателя",
                "verbose_name_plural": "Тип двигателей",
            },
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Обмен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обмен",
                "verbose_name_plural": "Обмен",
            },
        ),
        migrations.CreateModel(
            name="MarkOfCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark_name", models.CharField(max_length=50, verbose_name="Марка")),
            ],
            options={
                "verbose_name": "Марка",
                "verbose_name_plural": "Марки",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(max_length=50, verbose_name="Название региона"),
                ),
            ],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регион",
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration", models.CharField(max_length=50, verbose_name="Учет")),
            ],
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transmission_name",
                    models.CharField(max_length=40, verbose_name="Коробка передач"),
                ),
            ],
            options={
                "verbose_name": "Коробка передач",
                "verbose_name_plural": "Коробка передач",
            },
        ),
        migrations.CreateModel(
            name="WheelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wheel_type_name",
                    models.CharField(max_length=40, verbose_name="Руль"),
                ),
            ],
            options={
                "verbose_name": "Тип руля",
                "verbose_name_plural": "Тип руля",
            },
        ),
        migrations.CreateModel(
            name="YearOfProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_of_production",
                    models.CharField(max_length=100, verbose_name="Год выпуска"),
                ),
            ],
            options={
                "verbose_name": "Год выпуска",
                "verbose_name_plural": "Год выпуска",
            },
        ),
        migrations.CreateModel(
            name="Car_announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("urgency_of_announcement", models.BooleanField()),
                (
                    "body",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars_by_bodies",
                        to="main.bodytype",
                        verbose_name="Кузов",
                    ),
                ),
                (
                    "is_available",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars_by_availability",
                        to="main.availability",
                        verbose_name="Доступность",
                    ),
                ),
                (
                    "car_condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_query_name="cars_by_conditions",
                        to="main.carcondition",
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "car_meleage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars_by_meleages",
                        to="main.carmeleage",
                        verbose_name="Пробег",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        upload_to="cars_images/", verbose_name="Изображение"
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.car_announcement",
                        verbose_name="Фотографии",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cateory_name",
                    models.CharField(max_length=50, verbose_name="Категория"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategory",
                        to="main.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_categories",
                to="main.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_cities",
                to="main.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colors",
                to="main.colorofcar",
                verbose_name="Цвет",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="custom_clearence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_customs",
                to="main.customclearence",
                verbose_name="Растаможка",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="drive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_drives",
                to="main.drive",
                verbose_name="Привод",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="engine_capacity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_engine_capacities",
                to="main.enginecapacity",
                verbose_name="Объем двигателя",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="engine_power",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_engine_powers",
                to="main.enginepower",
                verbose_name="Мощность двигателя",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="engine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_engines",
                to="main.enginetype",
                verbose_name="Двигатель",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="exchange",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_exchanges",
                to="main.exchange",
                verbose_name="Обмен",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="mark",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_marks",
                to="main.markofcar",
                verbose_name="Марка",
            ),
        ),
        migrations.CreateModel(
            name="ModelOfCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="Модель")),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.markofcar",
                        verbose_name="Марка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель",
                "verbose_name_plural": "Модели",
            },
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_models",
                to="main.modelofcar",
                verbose_name="Модель",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_prices",
                to="main.price",
                verbose_name="Цена",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "avatar",
                    models.ImageField(upload_to="avatar/", verbose_name="Аватар"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_regions",
                to="main.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_registrations",
                to="main.registration",
                verbose_name="Учет",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="transmission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_transmissions",
                to="main.transmission",
                verbose_name="Тип коробки",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="wheel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_wheel_types",
                to="main.wheeltype",
                verbose_name="Руль",
            ),
        ),
        migrations.AddField(
            model_name="car_announcement",
            name="year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cars_by_years",
                to="main.yearofproduction",
                verbose_name="Год выпуска",
            ),
        ),
    ]
