# Generated by Django 5.2.4 on 2025-07-30 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_carimage_announcement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carannouncement",
            options={"verbose_name": "Объявление", "verbose_name_plural": "Объявления"},
        ),
        migrations.AlterModelOptions(
            name="carconfig",
            options={
                "verbose_name": "Конфигурация",
                "verbose_name_plural": "Конфигурации",
            },
        ),
        migrations.AlterModelOptions(
            name="drive",
            options={
                "verbose_name": "Тип привода",
                "verbose_name_plural": "Типы привода",
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "verbose_name": "Продвижение",
                "verbose_name_plural": "Продвижения",
            },
        ),
    ]
