# Generated by Django 5.2.4 on 2025-07-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_carannouncement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carannouncement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Статус объявления"),
        ),
    ]
