# Generated by Django 5.2.4 on 2025-07-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_carannouncement_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carannouncement",
            name="custom_clearence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.customclearence",
                verbose_name="Растаможка",
            ),
        ),
    ]
