# Generated by Django 5.2.4 on 2025-07-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_carannouncement_custom_clearence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carannouncement",
            old_name="car_meleage",
            new_name="car_mileage",
        ),
        migrations.RenameField(
            model_name="carannouncement",
            old_name="urgency_of_announcencenment",
            new_name="urgency",
        ),
    ]
