# Generated by Django 5.2.4 on 2025-08-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_rename_car_meleage_carannouncement_car_mileage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carannouncement",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="carannouncement",
            name="custom_clearence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.customclearence",
                verbose_name="Состояние",
            ),
        ),
    ]
