# Generated by Django 5.2.4 on 2025-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_carannouncement_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carannouncement",
            name="urgency",
            field=models.BooleanField(default=False, verbose_name="Срочно"),
        ),
    ]
