# Generated by Django 5.2.5 on 2025-11-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoannouncement',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='motoannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='motoannouncement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
