# Generated by Django 5.2.5 on 2025-10-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carconfig',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
