# Generated by Django 5.2.5 on 2025-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_carconfig_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carconfig',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
