# Generated by Django 5.2.5 on 2025-11-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_motoannouncement_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carannouncement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
