# Generated by Django 5.2.5 on 2025-10-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_carconfig_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='carannouncement',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
