# Generated by Django 5.2.5 on 2025-11-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_alter_carannouncement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoannouncement',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='motoannouncementimage',
            name='moto_announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auto.motoannouncement', verbose_name='Объявление о мототранспорте'),
        ),
    ]
