# Generated by Django 5.2.5 on 2025-10-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_carannouncement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carannouncement',
            name='custom_clearence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.customclearence', verbose_name='Растаможка'),
        ),
        migrations.AlterField(
            model_name='carannouncement',
            name='engine_power',
            field=models.DecimalField(decimal_places=1, max_digits=9, verbose_name='Мощность двигателя'),
        ),
    ]
