# Generated by Django 5.2.5 on 2025-10-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_alter_carannouncement_custom_clearence_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carannouncement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterUniqueTogether(
            name='carconfig',
            unique_together={('mark', 'model', 'generation', 'body', 'engine_type', 'engine_capacity', 'transmission', 'drive')},
        ),
        migrations.RemoveField(
            model_name='carconfig',
            name='slug',
        ),
    ]
