# Generated by Django 5.2.5 on 2025-10-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_alter_carannouncement_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carconfig',
            unique_together=set(),
        ),
    ]
