# Generated by Django 5.2.5 on 2025-11-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_alter_carconfig_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='car_images/', verbose_name='Фото'),
        ),
    ]
