# Generated by Django 5.2.5 on 2025-11-10 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_alter_carimage_image'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfMotorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип мототранспорта',
                'verbose_name_plural': 'Типы мототранспортов',
            },
        ),
        migrations.CreateModel(
            name='MotoAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена (сом)')),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.city', verbose_name='Город')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.generation', verbose_name='Серия')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.mark', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.model', verbose_name='Модель')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.region', verbose_name='Регион')),
                ('type_of_moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto.typeofmotorcycle', verbose_name='Тип мототранспорта')),
            ],
            options={
                'verbose_name': 'Объявление о мототранспорте',
                'verbose_name_plural': 'Объявления о мототранспорте',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotoAnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moto_announcements/', verbose_name='Изображение')),
                ('moto_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.motoannouncement', verbose_name='Объявление о мототранспорте')),
            ],
        ),
    ]
